-- MySQL Script generated by MySQL Workbench
-- Tue Sep 22 20:40:52 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema jobboard_db
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema jobboard_db
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `jobboard_db` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `jobboard_db` ;

-- -----------------------------------------------------
-- Table `jobboard_db`.`company`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobboard_db`.`company` (
  `company_id` INT NOT NULL AUTO_INCREMENT,
  `company_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`company_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jobboard_db`.`contra_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobboard_db`.`contra_type` (
  `contra_type_id` INT NOT NULL AUTO_INCREMENT,
  `contra_label` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`contra_type_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jobboard_db`.`offer`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobboard_db`.`offer` (
  `offer_id` INT NOT NULL AUTO_INCREMENT,
  `offer_title` VARCHAR(200) NOT NULL,
  `offer_description` TEXT NOT NULL,
  `offer_profile_sought` TEXT NOT NULL,
  `offer_contact_info` VARCHAR(255) NOT NULL,
  `date_publication` DATETIME NULL DEFAULT CURRENT_TIMESTAMP,
  `company_company_id` INT NULL DEFAULT NULL,
  `contra_type_id` INT NULL DEFAULT NULL,
  PRIMARY KEY (`offer_id`),
  INDEX `company_company_id` (`company_company_id` ASC) VISIBLE,
  INDEX `contra_type_id` (`contra_type_id` ASC) VISIBLE,
  CONSTRAINT `offer_ibfk_1`
    FOREIGN KEY (`company_company_id`)
    REFERENCES `jobboard_db`.`company` (`company_id`)
    ON DELETE CASCADE,
  CONSTRAINT `offer_ibfk_2`
    FOREIGN KEY (`contra_type_id`)
    REFERENCES `jobboard_db`.`contra_type` (`contra_type_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jobboard_db`.`technology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobboard_db`.`technology` (
  `technology_id` INT NOT NULL AUTO_INCREMENT,
  `technology_name` VARCHAR(100) NOT NULL,
  PRIMARY KEY (`technology_id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `jobboard_db`.`offer_technology`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `jobboard_db`.`offer_technology` (
  `offer_id` INT NOT NULL,
  `technology_id` INT NOT NULL,
  PRIMARY KEY (`offer_id`, `technology_id`),
  INDEX `technology_id` (`technology_id` ASC) VISIBLE,
  CONSTRAINT `offer_technology_ibfk_1`
    FOREIGN KEY (`offer_id`)
    REFERENCES `jobboard_db`.`offer` (`offer_id`)
    ON DELETE CASCADE,
  CONSTRAINT `offer_technology_ibfk_2`
    FOREIGN KEY (`technology_id`)
    REFERENCES `jobboard_db`.`technology` (`technology_id`)
    ON DELETE CASCADE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
